services:
  dev-environment:
    container_name: stilts-ai-dev
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: sleep infinity
    tty: true
    build:
      context: .
      dockerfile: dockerfile
    deploy:
      resources:
        limits:
          cpus: '5'