name: llm-training-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyter
  - matplotlib
  - pip:
      - torch
      - torchvision
      - torchaudio
      - accelerate
      - evaluate
      - sentencepiece
      - bitsandbytes
      - huggingface_hub
      - transformers
      - datasets
      - numpy
      - pandas
      - tqdm
      - scikit-learn  
      - llama-cpp-python